[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_protocol = esptool
debug_tool = esp-builtin
debug_speed = 12000
debug_init_break = tbreak setup

build_type = debug
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -O0 -ggdb3
build_src_filter = +<main.cpp>
lib_deps = 